---
title: "Maps of Meaning"
author: "Allan Wu"
date: "14/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(leaflet)
library(leaflet.extras)
library(rgdal)
require(plyr)
#source("cleaning_functions_pre_event.Rmd")
postcodes_loc <- read_csv("australian_postcodes.csv")
test <- read_csv("pre_event_cleaned_dummy.csv")
#data <- readxl::read_xlsx("Dummy Location 1_03.02.2021_Pre_Participants.xlsx")
```

# Maps


```{r}
postcodes_loc
```

```{r}
test$postcode = as.character(test$postcode)
test_joined <- left_join(test, postcodes_loc, by = c("postcode" = "postcode"))
test_joined <- test_joined %>% dplyr::distinct(...1, .keep_all = TRUE)
```




```{r}
test_clean = test_joined[!is.na(test_joined$age),]

# This function needs to have no NAs
getColor <- function(data) {
  sapply(data$age, function(age) {
  if(age <= 18) {
    "yellow"
  } else if(age <= 50) {
    "orange"
  } else {
    "red"
  } })
}

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor(test_clean)
)

# Map that provides info on each individual participant by one variable
m <-  leaflet(test_clean) %>%
  addTiles() %>%
  addMarkers(~long, ~lat, icon = icons, label = ~age, clusterOptions = markerClusterOptions)
m
```

```{r}
test_clean$age_group <- factor(test_clean$age_group, levels = c("age_under_5", "age_11_to_20", "age_21_to_30", "age_31_to_50", "age_51_to_70",  "age_over_71"))
test_clean$age_group <- mapvalues(test_clean$age_group, 
                                  from = c("age_under_5", "age_11_to_20", "age_21_to_30",
                                           "age_31_to_50", "age_51_to_70", "age_over_71"), 
                                  to = c("Under 5", "11 to 20", "21 to 30",
                                           "31 to 50", "51 to 70", "Over 71"))
test_clean.df <- split(test_clean, test_clean$age_group)

l <- leaflet() %>% addTiles()

names(test_clean.df) %>%
  purrr::walk(function(df) {
    l <<- l %>%
      addMarkers(data=test_clean.df[[df]],
                          lng=~long, lat=~lat,
                          label=~age,
                          popup=~age,
                          group = df,
                          clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                          labelOptions = labelOptions(noHide = F,
                                                       direction = 'auto'))
  })

l %>%
  addLayersControl(
    overlayGroups = names(test_clean.df),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
    htmlwidgets::onRender("
        function() {
            $('.leaflet-control-layers-list').prepend('<label style=\"text-align:center\">Age Groups</label>');
        }
    ")
```


```{r}
# Now all in a function
# Function:

# df: Pre event data with age, postcode

map_ages <- function(df){
  postcodes_loc <- read_csv("australian_postcodes.csv")
  df$postcode = as.character(df$postcode)
  df_joined <- left_join(df, postcodes_loc, by = c("postcode" = "postcode"))

  # Distinct on postcode dataset
  df_joined <- df_joined %>% dplyr::distinct(...1, .keep_all = TRUE)
  
  df_clean = df_joined[!is.na(df_joined$age),]
  #df_clean$age_group <- factor(df_clean$age_group, levels = c("age_under_5", "age_11_to_20", "age_21_to_30",
                                                               #   "age_31_to_50", "age_51_to_70",  "age_over_71"))
  # String cleaning for output
  df_clean <- df_clean %>% 
    mutate(age_group = str_replace_all(age_group, "age_", "")) %>%
    mutate(age_group = str_replace_all(age_group, "_", " ")) %>%
    mutate(age_group = str_to_sentence(age_group))
  
  df_clean$age_group <- factor(df_clean$age_group, levels = c("Under 5", "11 to 20", "21 to 30",
                                                              "31 to 50", "51 to 70",  "Over 71"))
  

  df_clean.df <- split(df_clean, df_clean$age_group)
  
  l <- leaflet() %>% addTiles()
  
  names(df_clean.df) %>%
    purrr::walk(function(df) {
      l <<- l %>%
        addMarkers(data=df_clean.df[[df]],
                            lng=~long, lat=~lat,
                            popup = paste(postcode %>% substitute() %>% deparse() %>% str_to_title(),
                                          ": ", df_clean.df[[df]]$postcode, 
                                          #"<br>", "Age: ", df_clean.df[[df]]$age, 
                                          sep = ""),
                            group = df,
                            clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                            labelOptions = labelOptions(noHide = F,
                                                         direction = 'auto'))
    })
  
  l %>%
    addLayersControl(
      overlayGroups = names(df_clean.df),
      options = layersControlOptions(collapsed = FALSE)
    ) %>%
      htmlwidgets::onRender("
          function() {
              $('.leaflet-control-layers-list').prepend('<label style=\"text-align:center\">Age Groups</label>');
          }
      ")
}
```


```{r}
map_ages(test)
```


```{r}
pre_clean
```


```{r}
### Preprocessing for map vis

read_postcodes <- function(){
  postcodes_loc <- read_csv("australian_postcodes.csv")
  return(postcodes_loc)
}

postcodes_loc <- read_postcodes()

# Function for cleaning pre-event data and joining with postcodes

pre_clean_map <- function(df, postcodes_loc){
  
  df$postcode = as.character(df$postcode)
  df$`...1` = seq(nrow(df)) 
  df_joined <- left_join(df, postcodes_loc, by = c("postcode" = "postcode"))
  df_joined <- df_joined %>% dplyr::distinct(...1, .keep_all = TRUE)
  
  return(df_joined)
}

# Function for cleaning post-event data and joining with postcodes

post_clean_map <- function(df, postcodes_loc){
  
  postcodes_loc <- read_csv("australian_postcodes.csv")
  df$postcode_event = as.character(df$postcode_event)
  df$`...1` = seq(nrow(df)) 
  df_joined <- left_join(df, postcodes_loc, by = c("postcode_event" = "postcode"))
  df_joined <- df_joined %>% dplyr::distinct(...1, .keep_all = TRUE)
  df_joined <- df_joined %>%
                  dplyr::rename(action_kpi = action_summary)
  
  return(df_joined)
}


```


```{r}
# Function for Participant Analysis

# Input:
# df - R DataFrame
# var1 - string of column name

map_one_variable <- function(df_joined, var1){
  
  df_joined[[var1]] <- df_joined[[var1]] %>% replace_na('Missing')
  
  df_clean <- df_joined
   #df_clean$age_group <- factor(df_clean$age_group, levels = c("age_under_5", "age_11_to_20", "age_21_to_30",
                                                               #   "age_31_to_50", "age_51_to_70",  "age_over_71"))
  # String cleaning for output
  df_clean <- df_clean %>% 
    mutate(age_group = str_replace_all(age_group, "age_", "")) %>%
    mutate(age_group = str_replace_all(age_group, "_", " ")) %>%
    mutate(age_group = str_to_sentence(age_group))
  
  clean_var <- var1 %>% 
    str_replace_all("_", " ") %>%
    str_to_title()
    
  
  df_clean$age_group <- factor(df_clean$age_group, levels = c("Under 5", "11 to 20", "21 to 30",
                                                              "31 to 50", "51 to 70",  "Over 71", "Missing"))
  
  df_clean[[var1]] <- factor(df_clean[[var1]])
  df_clean[[var1]] <- forcats::fct_relevel(df_clean[[var1]], "Missing", after = Inf)

  
  df_clean.df <- split(df_clean, df_clean[[var1]])
  
  l <- leaflet() %>% addTiles()
  
  names(df_clean.df) %>%
    purrr::walk(function(df) {
      l <<- l %>%
        addMarkers(data=df_clean.df[[df]],
                            lng=~long, lat=~lat,
                            popup = paste("Location: ", df_clean.df[[df]]$locality %>% str_to_title(), 
                                          #"<br>", "Age: ", df_clean.df[[df]]$age, 
                                          sep = ""),
                            group = df,
                            clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                            labelOptions = labelOptions(noHide = F,
                                                         direction = 'auto'))
    })
  
  l %>%
    addLayersControl(
      overlayGroups = names(df_clean.df),
      options = layersControlOptions(collapsed = FALSE)
    ) %>%
      htmlwidgets::onRender(paste("
          function() {
              $('.leaflet-control-layers-list').prepend('<label style=\"text-align:center\">", clean_var,"</label>');
          }
      ", sep = ""))
}

df_joined <- pre_clean_map(test, postcodes_loc)
map_one_variable(df_joined, "find_out_event")
```

```{r}
map_0_var <- function(df){
  postcodes_loc <- read_csv("australian_postcodes.csv")
  df$postcode = as.character(df$postcode)
  df$`...1` = seq(nrow(df)) 
  df_joined <- left_join(df, postcodes_loc, by = c("postcode" = "postcode"))
  df_joined <- df_joined %>% dplyr::distinct(...1, .keep_all = TRUE)
  
  m <- leaflet(df_joined) %>%
  addTiles() %>%
  addMarkers(~long, ~lat, popup = paste("Location: ", df_joined$locality %>% str_to_title(),
                                          sep = ""), clusterOptions = markerClusterOptions)
m
}
map_0_var(test)
```


```{r}
# Loading post-event data

post = read_csv("postEvent2.csv")
```


```{r}
# Function for KPIs

# Input:
# df - R DataFrame
map_kpi <- function(df_joined, kpi){
  
  if (kpi == "action"){
    kpi_col = "action_kpi"
  }
  if (kpi == "community"){
    kpi_col = "community_kpi"
  }
  if (kpi == "learning"){
    kpi_col = "learning_kpi"
  }
  
  df_joined <- df_joined %>% dplyr::group_by(postcode_event, lat, long, locality) %>%
  dplyr::summarise(
    vis_kpi = mean(get(kpi_col)),
    count = n()
  )
  
  # Colour Palette
  pal <- colorNumeric("viridis", df_joined$vis_kpi, n = 5)
  
  # Rescaling count column to 0-50
  df_joined$count_scaled <- df_joined$count %>% scale(center = FALSE, scale = max(df_joined$count, na.rm = TRUE)/50)
  
  # Map
  m <- leaflet(df_joined) %>%
  addTiles() %>%
  addCircleMarkers(~long, ~lat, 
                   popup = paste("Location: ", df_joined$locality %>% str_to_title(),
                                 "<br>", "Average KPI: ", round(df_joined$vis_kpi, 2),
                                 "<br>", "Number of Participants: ", df_joined$count, sep = ""),
                   color = ~pal(vis_kpi), fillOpacity = 0.5,
                   radius = ~count_scaled
                   ) %>%
    addLegend(pal = pal, values = ~vis_kpi, opacity = 1.0,
              title = paste((kpi_col %>% str_split("_"))[[1]][1] %>% str_to_title(), 'KPI'),
              labFormat = labelFormat(transform = function(x) round(x, 2)))
m
}

```

```{r}
df_joined <- post_clean_map(post, postcodes_loc)
map_kpi(df_joined, "action")
map_kpi(df_joined, "community")
map_kpi(df_joined, "learning")
```

```{r}
# Function for KPIs

# Input:
# df - R DataFrame
map_kpi_filter <- function(df, kpi, var1){
  postcodes_loc <- read_csv("australian_postcodes.csv")
  df$postcode_event = as.character(df$postcode_event)
  df$`...1` = seq(nrow(df)) 
  df_joined <- left_join(df, postcodes_loc, by = c("postcode_event" = "postcode"))
  df_joined <- df_joined %>% dplyr::distinct(...1, .keep_all = TRUE)
  df_joined <- df_joined %>%
                  dplyr::rename(action_kpi = action_summary)
  
  if (kpi == "action"){
    kpi_col = "action_kpi"
  }
  if (kpi == "community"){
    kpi_col = "community_kpi"
  }
  if (kpi == "learning"){
    kpi_col = "learning_kpi"
  }
  
  df_joined[[var1]] <- df_joined[[var1]] %>% replace_na('Missing')
  
  df_joined <- df_joined %>% dplyr::group_by(postcode_event, lat, long, locality, get(var1)) %>%
  dplyr::summarise(
    vis_kpi = mean(get(kpi_col)),
    count = n()
  )
  
  # Colour Palette
  pal <- colorNumeric("viridis", df_joined$vis_kpi, n = 5)
  
  # Rescaling count column to 0-50
  df_joined$count_scaled <- df_joined$count %>% scale(center = FALSE, scale = max(df_joined$count, na.rm = TRUE)/50)
  
  # Map
  m <- leaflet(df_joined) %>%
  addTiles() %>%
  addCircleMarkers(~long, ~lat, 
                   popup = paste("Location: ", df_joined$locality %>% str_to_title(),
                                 "<br>", "Average KPI: ", round(df_joined$vis_kpi, 2),
                                 "<br>", "Number of Participants: ", df_joined$count, sep = ""),
                   color = ~pal(vis_kpi), fillOpacity = 0.5,
                   radius = ~count_scaled
                   ) %>%
    addLegend(pal = pal, values = ~vis_kpi, opacity = 1.0,
              title = paste((kpi_col %>% str_split("_"))[[1]][1] %>% str_to_title(), 'KPI'),
              labFormat = labelFormat(transform = function(x) round(x, 2)))
m
}

  
  df_clean <- df_joined
   #df_clean$age_group <- factor(df_clean$age_group, levels = c("age_under_5", "age_11_to_20", "age_21_to_30",
                                                               #   "age_31_to_50", "age_51_to_70",  "age_over_71"))
  # String cleaning for output
  df_clean <- df_clean %>% 
    mutate(age_group = str_replace_all(age_group, "age_", "")) %>%
    mutate(age_group = str_replace_all(age_group, "_", " ")) %>%
    mutate(age_group = str_to_sentence(age_group))
  
  clean_var <- var1 %>% 
    str_replace_all("_", " ") %>%
    str_to_title()
    
  
  df_clean$age_group <- factor(df_clean$age_group, levels = c("Under 5", "11 to 20", "21 to 30",
                                                              "31 to 50", "51 to 70",  "Over 71", "Missing"))
  
  df_clean[[var1]] <- factor(df_clean[[var1]])
  df_clean[[var1]] <- forcats::fct_relevel(df_clean[[var1]], "Missing", after = Inf)

  
  df_clean.df <- split(df_clean, df_clean[[var1]])
  
  l <- leaflet() %>% addTiles()
  
  names(df_clean.df) %>%
    purrr::walk(function(df) {
      l <<- l %>%
        addMarkers(data=df_clean.df[[df]],
                            lng=~long, lat=~lat,
                            popup = paste("Location: ", df_clean.df[[df]]$locality %>% str_to_title(), 
                                          #"<br>", "Age: ", df_clean.df[[df]]$age, 
                                          sep = ""),
                            group = df,
                            clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                            labelOptions = labelOptions(noHide = F,
                                                         direction = 'auto'))
    })
  
  l %>%
    addLayersControl(
      overlayGroups = names(df_clean.df),
      options = layersControlOptions(collapsed = FALSE)
    ) %>%
      htmlwidgets::onRender(paste("
          function() {
              $('.leaflet-control-layers-list').prepend('<label style=\"text-align:center\">", clean_var,"</label>');
          }
      ", sep = ""))
```