---
title: "cleaning_functions_post_event"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library('readxl')
library(plyr)
library(tidyverse)
library(stringr)
library(readr)
library(tidyr)

# definitions
attributes_ls <- c("Email", "What were your biggest learnings from the activity? (Select all 6 that apply)?", "What did you enjoy most about the community? (Select all 5 that apply)", "Select the appropriate response you feel represents your experience [Use second-hand or borrowed items] (Action)", "Select the appropriate response you feel represents your experience [Reduce plastic usage] (Action)", "Select the appropriate response you feel represents your experience [Get a compost or worm farm] (Action)", "Select the appropriate response you feel represents your experience [Drop E-waste at collection facility eg. Officeworks] (Action)", "Select the appropriate response you feel represents your experience [Contact Council for specific waste separation information] (Action)", "Select the appropriate response you feel represents your experience [Using skills learnt from waste wise workshops] (Action)", "Select the appropriate response you feel represents your experience [new option] (Action)", "On a scale of 1-5, how would you rate your environmental habits after the activity?", "How would you prefer to find out about Seaside Scavenge events?", "Please let us know any overall feedback or other comments!", "We would like to conduct a follow-up chat with participants that have changed their perspective and approach to waste and recycling since participating in the Scavenge event. The interview is voluntary, conducted over the phone at a time that best suits you and will take up to 20 minutes. All answers are confidential and this insight will be used to highlight individual changes around waste in the local community.") 

colnames_ls <- c("email", "action", "community", "learning", "invested_environmental_impact", "find_out_event")

```


```{r, warning=FALSE}

############################## PREPROCESSING #############################

# cleans up single excel file for columns required
# input is dataframe pre_event_all and name of excel file is excel_name_ls
# output is cleaned dataframe

preprocessing_fn_post <- function(post_event_all,excel_name_ls) {
  
  # pre_event_data = clean_names(pre_event_data)
  
  ## CODE TO ADD KPI VALUES IN ##
  
  ## CODE TO GET ENVIRONMENTAL HABITS 
  
  
  # colnames(post_event_data) <- colnames_ls
  
  # adds location and year as columns
  name_split = strsplit(excel_name_ls, "_", fixed = TRUE)
  date = name_split[[1]][2]
  date_split = strsplit(date, ".", fixed = TRUE)
  post_event_data <- post_event_data %>% mutate(location = name_split[[1]][1])
  post_event_data <- post_event_data %>% mutate(year = date_split[[1]][3])
  
  View(post_event_data)

  


  return (post_event_data)

}
preprocessing_fn_post()

# converts required values to numeric
valid_numeric <- function(input) {
    input_numeric = as.numeric(input)
    input_numeric = ifelse(input_numeric >= 0, input_numeric, NA)    

  return (input_numeric)
}

# validates postcode values
valid_postcode <- function(input) {
  input_numeric = as.numeric(input)
  input_numeric = ifelse(input_numeric >= 1000 & input_numeric <=9999, input_numeric, NA)
  
  return (as.character(input_numeric))
}

## Code to call functions ##
# pre_event_data = preprocessing_fn("pre-event_responses_v2.xlsx")


```

## Modified Reading Function for google drive 
```{r}
nullConversion = function(x){
    x %>% 
    rowwise() %>% 
    mutate_all(function(x) ifelse(is.null(unlist(x)), NA, as.character(unlist(x))))
}

## converts required values to numeric
valid_numeric <- function(input) {
  input[vapply(input, is.null, TRUE)] = NA
  input = unlist(input)
  input_numeric = as.numeric(input)
  input_numeric = ifelse(input_numeric >= 0, input_numeric, NA)    
  
  return (input_numeric)
}


# validates postcode values
valid_postcode <- function(input) {
  input[vapply(input, is.null, TRUE)] = NA
  input = unlist(input)
  input_numeric = as.numeric(input)
  input_numeric = ifelse(input_numeric >= 1000 & input_numeric <=9999, input_numeric, NA)
  
  return (as.character(input_numeric))
}


## Processing one dataset
preprocessing_fn <- function(pre_event_all = dataframe_ls,excel_name_ls = excel_ls_name) {

  pre_event_data = subset(pre_event_all, select = attributes_ls)
  colnames(pre_event_data) <- colnames_ls
  
  pre_event_data_numeric = as.data.frame(lapply(nullConversion(pre_event_data[, numeric_ls]), valid_numeric))
  
  pre_event_data = pre_event_data[, !(names(pre_event_data) %in% numeric_ls)]
  
  pre_event_data$postcode = valid_postcode(pre_event_data$postcode)
  
  pre_event_data = cbind(pre_event_data, pre_event_data_numeric)
  
  # creates new column for correct age bin of eventbrite responders
  pre_event_data$age_group <- cut(pre_event_data$age, breaks = c(0, 5, 10, 20, 30, 50, 70, Inf), labels = age_range_options,  right = FALSE, include.lowest = TRUE) %>% 
    factor(age_range_options)

  ### Adding extra entries of people as rows ###
  section = (pre_event_data %>% select(postcode, age_range_options, age_group))
  for (num in 1:length(age_range_options)) {
    single_age_section = section %>% filter(!!sym(age_range_options[num]) > 0)
    for (row in 1:nrow(single_age_section)) {
      duplicates <- single_age_section[row, age_range_options[num]]
      for (duplicate_no in 1:duplicates) {
        pre_event_data = pre_event_data %>% add_row(postcode = 
                                                      single_age_section[row, "postcode"],
                                                    age_group = age_range_options[num])      
      }
    }    
  }
  
  # adds location and year as columns
  name_split = strsplit(excel_name_ls, "_", fixed = TRUE)
  date = name_split[[1]][2]
  date_split = strsplit(date, ".", fixed = TRUE)
  pre_event_data <- pre_event_data %>% mutate(location = name_split[[1]][1])
  pre_event_data <- pre_event_data %>% mutate(year = date_split[[1]][3])

  return (pre_event_data)
  
}


## Processing multiple datasets ## SHOULD BE SAME AS PRE EVENT FN !!!

preprocessing_multiple_fn <- function(dataframe_ls, excel_ls_name) {
  # Changed [1] to [[1]]
  if (length(dataframe_ls) == 1){
    combined_data = preprocessing_fn(post_event_all = dataframe_ls[[1]], excel_name_ls = excel_ls_name[[1]])
  }else{
    combined_data <- preprocessing_fn(dataframe_ls[[1]], excel_ls_name[[1]])
    i = 2
    for (excel_name in excel_ls_name[2:length(excel_ls_name)]) {
      # Changed [i] to [[i]]
      combined_data <- rbind(combined_data, preprocessing_fn(dataframe_ls[[i]], excel_name))
      i = i + 1
    }
  }
  return (combined_data)
}

```



```{r}
########################### PREPROCESSING MULTIPLE ##########################
filenames = c("Dummy Location 1_03.02.2021_Pre_Participants.xlsx","Dummy Location 2 !!`''`-^%##@'_03.02.2020_Pre_Participants.xlsx")

# cleans up multiple excel file for columns required
# input is multiple excel files as a list
# output is total cleaned dataframe
preprocessing_multiple_fn <- function(dataframe_ls, excel_ls_name) {
    # Changed [1] to [[1]]
  combined_data <- preprocessing_fn(dataframe_ls[[1]], excel_ls_name[[1]])
  i = 2
  for (excel_name in excel_ls_name[2:length(excel_ls_name)]) {
    # Changed [i] to [[i]]
    combined_data <- rbind(combined_data, preprocessing_fn(dataframe_ls[[i]], excel_name))
    i = i + 1
  }
  return (combined_data)
}

## Code to call functions ##
combined_data = preprocessing_multiple_fn(dataframe_ls = list(data,data),   excel_ls_name=filenames)

## Code to get csv
# write.csv(combined_data, "pre_event_cleaned_combined_dummy.csv")


```


```{r}
write.csv(pre_event_data, "pre_event_cleaned_dummy.csv")


pre_event_cleaned <- read.csv("pre_event_cleaned_dummy.csv")

glimpse(pre_event_cleaned)
#barplot of ages of those who filled the survey
pre_event_cleaned %>% 
  ggplot() + aes(x=age_group)+
  geom_bar()

#Histogram for ages of people who filled out the survey 

p <- pre_event_cleaned %>% 
  ggplot(aes(x = age)) +
  geom_histogram()
p

#getting rid of the NAs
pre_event_cleaned[is.na(pre_event_cleaned)]  <- 0
glimpse(pre_event_cleaned)

age_buckets <- c('age_under_5', "age_5_to_10", "age_11_to_20", "age_21_to_30", "age_31_to_50", "age_51_to_70", "age_over_71")


#total_in_age_bucket <- c(rowsum(pre_event_cleaned$age_under_5), rowsum(pre_event_cleaned$age_5_to_10), rowsum(pre_event_cleaned$age_11_to_20), rowsum(pre_event_cleaned$age_21_to_30), rowsum(pre_event_cleaned$age_31_to_50), rowsum(pre_event_cleaned$age_51_to_70), rowsum(pre_event_cleaned$age_over_71))


#total_in_age_bucket <- rowSums(pre_event_cleaned[7,13])
#x <- rowSums(pre_event_cleaned$age_under_5, pre_event_cleaned$age_5_to_10)
#x

pre_event_cleaned_rowsums <- colSums(pre_event_cleaned[7:13])
count_ages <- c(pre_event_cleaned_rowsums)

age_df <- data.frame(count_ages)
age_df

age_df %>% 
  ggplot() + aes(x = "ages") + geom_bar()

#age_df <- data.frame(age_buckets, count_ages)

#age_df <-as.data.frame(t(age_df))

#a <- barplot(age_df$,
             xlab = "age_buckets",
             ylab = "count_ages" )

#age_df <- data.frame(age_buckets, count_ages)

#age_df <-as.data.frame(t(age_df))

#a <- barplot(age_df$,
             #xlab = "age_buckets",
             #ylab = "count_ages" )
```


