---
title: "cleaning_functions_pre_event"
output: html_document
---
# Why is GIT like this :(
# biggest sadge :((((
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library(readxl)
library(plotly)
library(janitor)
library(tidyverse)

# definitions
attributes_ls <- c("Email", "What pronoun do you identify with?", "Age", "Postcode", "How many people under (5) years are you signing up for?", "How many people in the age range(5-10) are you signing up for?", "How many people in the age range(11-20) are you signing up for?", "How many people in the age range(21-30) are you signing up for?", "How many people in the age range(31-50) are you signing up for?", "How many people in the age range(51-70) are you signing up for?", "How many people in the age range(71+) are you signing up for?", "Have you previously attended an organised clean-up event (hosted by any organisation)?", "On a scale of 1 to 5, where 1 is not engaged at all and 5 is very engaged, how engaged are you in making changes that positively impact the environment?", "How did you find out about this event?", "Are you of Aboriginal or Torres Strait Islander Origin?" ) 

colnames_ls <- c("email", "gender", "age", "postcode", "age_under_5", "age_5_to_10","age_11_to_20","age_21_to_30","age_31_to_50","age_51_to_70","age_over_71", "previous_attendance", "pre_environmental_impact", "find_out_event", "origin" )

total_colnames_ls <- c("email", "gender", "age", "postcode", "age_under_5", "age_5_to_10","age_11_to_20","age_21_to_30","age_31_to_50","age_51_to_70","age_over_71", "previous_attendance", "pre_environmental_impact", "find_out_event", "age_group", "location", "year", "origin", "postcode_event")

merge_colnames_ls <- c("location", "year")

age_range_options <- c("age_under_5", "age_5_to_10", "age_11_to_20", "age_21_to_30", "age_31_to_50", "age_51_to_70", "age_over_71")


numeric_ls <- c("age_under_5", "age_5_to_10", "age_11_to_20", "age_21_to_30", "age_31_to_50", "age_51_to_70", "age_over_71", "age", "pre_environmental_impact")


```

```{r, warning=FALSE}
# 
# ############################## PREPROCESSING #############################
# 
# # cleans up single excel file for columns required
# # input is dataframe pre_event_all and name of excel file is excel_name_ls
# # output is cleaned dataframe
# 
# preprocessing_fn <- function(pre_event_all,excel_name_ls) {
#   
#   # pre_event_all = read_excel(excel_name)
#   
#   # names(pre_event_all)
#   
#   pre_event_data = subset(pre_event_all, select = attributes_ls)
#   # pre_event_data = clean_names(pre_event_data)
#   colnames(pre_event_data) <- colnames_ls
#   # pre_event_data$age
#   # pre_event_data %>% lapply(numeric_ls, valid_numeric)
#     
#     
#   # pre_event_data_numeric = apply(pre_event_data[ , numeric_ls], 2, valid_numeric)   
#   
#   pre_event_data_numeric = as.data.frame(lapply(pre_event_data[, numeric_ls], valid_numeric))
#   
#   
#   pre_event_data = pre_event_data[, !(names(pre_event_data) %in% numeric_ls)]
#   
#   pre_event_data$postcode = valid_postcode(pre_event_data$postcode)
#   
#   pre_event_data = cbind(pre_event_data, pre_event_data_numeric)
# 
#   # creates new column for correct age bin of eventbrite responders
#   pre_event_data$age_group <- cut(pre_event_data$age, breaks = c(0, 5, 10, 20, 30, 50, 70, Inf), labels = age_range_options,  right = FALSE, include.lowest = TRUE)
#   
# 
#   ### Adding extra entries of people as rows ###
# 
#   section = (pre_event_data %>% select(postcode, age_range_options, age_group))
# 
#   
#   # !!sym(input$var_xaxis)
#   
#   for (num in 1:length(age_range_options)) {
#     single_age_section = section %>% filter(!!sym(age_range_options[num]) > 0)
#     for (row in 1:nrow(single_age_section)) {
#       duplicates <- single_age_section[row, age_range_options[num]]
#       for (duplicate_no in 1:duplicates) {
#         pre_event_data = pre_event_data %>% add_row(postcode = 
#                                                       single_age_section[row, "postcode"],
#                                                     age_group = age_range_options[num])      
#       }
#     }    
#   }
#   
#   # adds location and year as columns
#   name_split = strsplit(excel_name_ls, "_", fixed = TRUE)
#   date = name_split[[1]][2]
#   date_split = strsplit(date, ".", fixed = TRUE)
#   pre_event_data <- pre_event_data %>% mutate(location = name_split[[1]][1])
#   pre_event_data <- pre_event_data %>% mutate(year = date_split[[1]][3])
#  
# 
# 
#     
# 
#   # View(single_age_section)
#   # View(pre_event_data)
# 
# 
# 
#   return (pre_event_data)
# 
# }
# 
# # converts required values to numeric
# valid_numeric <- function(input) {
#     input_numeric = as.numeric(input)
#     input_numeric = ifelse(input_numeric >= 0, input_numeric, NA)    
# 
#   return (input_numeric)
# }
# 
# # validates postcode values
# valid_postcode <- function(input) {
#   input_numeric = as.numeric(input)
#   input_numeric = ifelse(input_numeric >= 1000 & input_numeric <=9999, input_numeric, NA)
#   
#   return (as.character(input_numeric))
# }
# 
# ## Code to call functions ##
# # pre_event_data = preprocessing_fn("pre-event_responses_v2.xlsx")
# 
# data = readxl::read_xlsx("Dummy Location 1_03.02.2021_Pre_Participants.xlsx")
# pre_event_data = preprocessing_fn(pre_event_all = data,excel_name_ls = "Dummy Location 1_03.02.2021_Pre_Participants.xlsx")
# 
# pre_event_data = preprocessing_fn(list(data),list("Dummy Location 1_03.02.2021_Pre_Participants.xlsx"))
# 
# 
# # pre_event_all = read_excel("Dummy Location 1_03.02.2021_Pre_Participants.xlsx")
# # pre_event_data = preprocessing_fn(pre_event_all, "Dummy Location 1_03.02.2021_Pre_Participants.xlsx")
# 
# # summary(pre_event_data)
# 


```

## Modified Reading Function for google drive 
```{r}
nullConversion = function(x){
    x %>% 
    rowwise() %>% 
    mutate_all(function(x) ifelse(is.null(unlist(x)), NA, as.character(unlist(x))))
}

## converts required values to numeric
valid_numeric <- function(input) {
  input[vapply(input, is.null, TRUE)] = NA
  input = unlist(input)
  input_numeric = as.numeric(input)
  input_numeric = ifelse(input_numeric >= 0, input_numeric, NA)    
  
  return (input_numeric)
}

# validates postcode values
valid_postcode <- function(input) {
  input[vapply(input, is.null, TRUE)] = NA
  input = unlist(input)
  input_numeric = as.numeric(input)
  input_numeric = ifelse(input_numeric >= 1000 & input_numeric <=9999, input_numeric, NA)
  
  return (as.character(input_numeric))
}


## Processing one dataset
preprocessing_fn <- function(pre_event_all = dataframe_ls,excel_name_ls = excel_ls_name) {

  pre_event_data = subset(pre_event_all, select = attributes_ls)
  colnames(pre_event_data) <- colnames_ls
  
  pre_event_data_numeric = as.data.frame(lapply(nullConversion(pre_event_data[, numeric_ls]), valid_numeric))
  
  pre_event_data = pre_event_data[, !(names(pre_event_data) %in% numeric_ls)]
  
  pre_event_data$postcode = valid_postcode(pre_event_data$postcode)
  
  pre_event_data = cbind(pre_event_data, pre_event_data_numeric)
  
  # creates new column for correct age bin of eventbrite responders
  pre_event_data$age_group <- cut(pre_event_data$age, breaks = c(0, 5, 10, 20, 30, 50, 70, Inf), 
                                  labels = age_range_options,  right = FALSE, include.lowest = TRUE) %>% 
    factor(age_range_options)
  
  # Convert invested enviro impact to factor
  pre_event_data$pre_environmental_impact = factor(pre_event_data$pre_environmental_impact, levels = c(1,2,3,4,5))
  
  # pre_event_data$pre_environmental_impact = factor(pre_event_data$pre_environmental_impact, levels = c(1,2,3,4,5))


  ### Adding extra entries of people as rows ###
  section = (pre_event_data %>% select(postcode, age_range_options, age_group))
  for (num in 1:length(age_range_options)) {
    single_age_section = section %>% filter(!!sym(age_range_options[num]) > 0)
    for (row in 1:nrow(single_age_section)) {
      duplicates <- single_age_section[row, age_range_options[num]]
      for (duplicate_no in 1:duplicates) {
        pre_event_data = pre_event_data %>% add_row(postcode = 
                                                      single_age_section[row, "postcode"],
                                                    age_group = age_range_options[num])      
      }
    }    
  }
  
  # adds location and year as columns
  name_split = strsplit(excel_name_ls, "_", fixed = TRUE)
  date = name_split[[1]][3]
  date_split = strsplit(date, ".", fixed = TRUE)
  pre_event_data <- pre_event_data %>% mutate(location = name_split[[1]][1])
  pre_event_data <- pre_event_data %>% mutate(postcode_event = name_split[[1]][2])

  pre_event_data <- pre_event_data %>% mutate(year = date_split[[1]][3])

  return (pre_event_data)
  
}


## Processing multiple datasets

preprocessing_multiple_fn <- function(dataframe_ls, excel_ls_name) {
  # Changed [1] to [[1]]
  if (length(dataframe_ls) == 1){
    combined_data = preprocessing_fn(pre_event_all = dataframe_ls[[1]], excel_name_ls = excel_ls_name[[1]])
  }else{
    combined_data <- preprocessing_fn(dataframe_ls[[1]], excel_ls_name[[1]])
    i = 2
    for (excel_name in excel_ls_name[2:length(excel_ls_name)]) {
      # Changed [i] to [[i]]
      combined_data <- rbind(combined_data, preprocessing_fn(dataframe_ls[[i]], excel_name))
      i = i + 1
    }
  }
  return (combined_data)
}

```

```{r}
excel_name_ls = "Byron Bay_2481_28.09.2020_Pre_Participants.xlsx"

name_split = strsplit(excel_name_ls, "_", fixed = TRUE)
date = name_split[[1]][3]
date_split = strsplit(date, ".", fixed = TRUE)
location = name_split[[1]][1]
postcode_event = name_split[[1]][2]

year = date_split[[1]][3]

print(location)
print(postcode_event)
print(year)
```


```{r}
########################### PREPROCESSING MULTIPLE ##########################
filenames = c("Dummy Location 1_03.02.2021_Pre_Participants.xlsx","Dummy Location 2 !!`''`-^%##@'_03.02.2020_Pre_Participants.xlsx")

# cleans up multiple excel file for columns required
# input is multiple excel files as a list
# output is total cleaned dataframe
preprocessing_multiple_fn <- function(dataframe_ls, excel_ls_name) {
    # Changed [1] to [[1]]
  combined_data <- preprocessing_fn(dataframe_ls[[1]], excel_ls_name[[1]])
  i = 2
  for (excel_name in excel_ls_name[2:length(excel_ls_name)]) {
    # Changed [i] to [[i]]
    combined_data <- rbind(combined_data, preprocessing_fn(dataframe_ls[[i]], excel_name))
    i = i + 1
  }
  return (combined_data)
}

## Code to call functions ##
combined_data = preprocessing_multiple_fn(dataframe_ls = list(data,data),   excel_ls_name=filenames)

## Code to get csv
# write.csv(combined_data, "pre_event_cleaned_combined_dummy.csv")


```


```{r}

########################## AMOUNT OF ATTENDEES ###########################

# returns number of total attendees
# input is preprocessed dataframe
# output is integer
attendees_total <- function(pre_event_data) {
    eventbrite_tot = attendees_eventbrite(pre_event_data)
    other_tot = sum(rowSums(pre_event_data[,age_range_options], na.rm=TRUE))
    # eventbrite_tot + other_tot
    return (eventbrite_tot + other_tot)
}

# returns total number of respondents to eventbrite form
# input is preprocessed dataframe
# output is integer
attendees_eventbrite <- function(pre_event_data) {
    return (nrow(pre_event_data))
}

# returns number of total attendees answering "Age" question correctly (TOTAL)
# input is preprocessed dataframe
# output is integer

attendees_age_correct_total <- function(pre_event_data) {
    eventbrite_tot = attendees_age_correct_eventbrite(pre_event_data)
    other_tot = sum(rowSums(pre_event_data[,age_range_options], na.rm=TRUE))
    return (eventbrite_tot + other_tot)
}

# returns number of total attendees answering "Age" question correctly (Only from people who HAVE filled out eventbrite)
# input is preprocessed dataframe
# output is integer

attendees_age_correct_eventbrite <- function(pre_event_data) {
    valid_value = ifelse(is.na(pre_event_data$age), 0, 1)
    return (sum(valid_value))
}

# returns number of total attendees answering "Postcode" question correctly
# input is preprocessed dataframe
# output is integer

attendees_correct_postcode <- function(pre_event_data) {
    valid_value = ifelse(is.na(pre_event_data$postcode), 0, 1)
    return (sum(valid_value))
}

## Code to call functions ##
attendees_total(pre_event_data)
attendees_eventbrite(pre_event_data)
attendees_age_correct_eventbrite(pre_event_data)
attendees_age_correct_total(pre_event_data)
attendees_correct_postcode(pre_event_data)
```


```{r}

########################## PRONOUN DISTRIBUTION ##########################

# returns number of attendees answering "She/He/Their/Other" for question "What pronoun do you identify with"
# input is preprocessed dataframe and specified pronoun
# output is table

pronoun_count <- function(pre_event_data) {
  pronoun_table = table(pre_event_data$pronoun) %>% as.data.frame()
  colnames(pronoun_table) <- c("Pronoun", "Frequency")
  return(pronoun_table)
}

## Code to call functions ##
pronoun_count(pre_event_data)

```


```{r}

############################ AGE DISTRIBUTION ############################

# returns number of attendees in a certain age range (TOTAL)
# input is preprocessed dataframe and specified age range
# output is table
age_count_total <- function(pre_event_data) {
  age_count_eventbrite_table = table(pre_event_data$age_group)
  age_count_not_eventbrite_table = colSums(pre_event_data[, age_range_options], na.rm=TRUE) 
  age_count_total_table = colSums(rbind(age_count_eventbrite_table, age_count_not_eventbrite_table)) %>% as.data.frame()
  colnames(age_count_total_table) <- c("Frequency")

  return(age_count_total_table)
}

# returns number of attendees in a certain age range (Only from people who HAVE filled out eventbrite)
# input is preprocessed dataframe and specified age range
# output is table

age_count_eventbrite <- function(pre_event_data) {
  age_count_eventbrite_table = table(pre_event_data$age_group) %>% as.data.frame()
  colnames(age_count_eventbrite_table) <- c("Age", "Frequency")
  return(age_count_eventbrite_table)
}

# returns number of attendees in a certain age range (Only from people who HAVEN'T filled out eventbrite)
# input is preprocessed dataframe and specified age range
# output is table

age_count_not_eventbrite <- function(pre_event_data) {
  age_count = colSums(pre_event_data[, age_range_options], na.rm=TRUE) %>% as.data.frame()
  colnames(age_count) <- c("Frequency")
  return(age_count)
}

## Code to call functions ##
age_count_eventbrite(pre_event_data)
age_count_not_eventbrite(pre_event_data)
age_count_total(pre_event_data)

```


```{r}

################### ENVIRONMENTAL HABITS DISTRIBUTION ####################

# returns number of attendees answering "Yes/No/Can't Remember" for question "Have you previously attended an organised clean-up event (hosted by any organisation)?"
# input is preprocessed dataframe and specified answer
# output is table

previous_event_count <- function(pre_event_data) {
  previous_event_table = table(pre_event_data$previous_attendance)  %>% as.data.frame()
  colnames(previous_event_table) <- c("Previous Attendance", "Frequency")
  return(previous_event_table)
}

# returns number of attendees answering "1/2/3/4/5" for question "On a scale of 1-5 how invested are you in environmental impact?(1 being the least invested)"
# input is preprocessed dataframe and specified answer
# output is table

pre_environmental_impact_count <- function(pre_event_data) {
  pre_environmental_impact_table = table(pre_event_data$pre_environmental_impact) %>% as.data.frame()
  colnames(pre_environmental_impact_table) <- c("Invested Rating", "Frequency")
  return(pre_environmental_impact_table)
}

## Code to call functions ##
previous_event_count(pre_event_data)
pre_environmental_impact_count(pre_event_data)

```

```{r}

######################### MARKETING DISTRIBUTION #########################

# returns number of attendees answering a certain marketing type for question "How did you find out about this event?"
# input is preprocessed dataframe and specified answer
# output is vector


marketing_count <- function(pre_event_data) {
  marketing_table = table(pre_event_data$find_out_event) %>% as.data.frame()
  colnames(marketing_table) <- c("Marketing Type", "Frequency")
  return(marketing_table)
}

## Code to call functions ##
marketing_count(pre_event_data)

```



```{r}
write.csv(pre_event_data, "pre_event_cleaned_dummy.csv")


pre_event_cleaned <- read.csv("pre_event_cleaned_dummy.csv")

glimpse(pre_event_cleaned)
#barplot of ages of those who filled the survey
pre_event_cleaned %>% 
  ggplot() + aes(x=age_group)+
  geom_bar()

#Histogram for ages of people who filled out the survey 

p <- pre_event_cleaned %>% 
  ggplot(aes(x = age)) +
  geom_histogram()
p

#getting rid of the NAs
pre_event_cleaned[is.na(pre_event_cleaned)]  <- 0
glimpse(pre_event_cleaned)

age_buckets <- c('age_under_5', "age_5_to_10", "age_11_to_20", "age_21_to_30", "age_31_to_50", "age_51_to_70", "age_over_71")


#total_in_age_bucket <- c(rowsum(pre_event_cleaned$age_under_5), rowsum(pre_event_cleaned$age_5_to_10), rowsum(pre_event_cleaned$age_11_to_20), rowsum(pre_event_cleaned$age_21_to_30), rowsum(pre_event_cleaned$age_31_to_50), rowsum(pre_event_cleaned$age_51_to_70), rowsum(pre_event_cleaned$age_over_71))


#total_in_age_bucket <- rowSums(pre_event_cleaned[7,13])
#x <- rowSums(pre_event_cleaned$age_under_5, pre_event_cleaned$age_5_to_10)
#x

pre_event_cleaned_rowsums <- colSums(pre_event_cleaned[7:13])
count_ages <- c(pre_event_cleaned_rowsums)

age_df <- data.frame(count_ages)
age_df

age_df %>% 
  ggplot() + aes(x = "ages") + geom_bar()

#age_df <- data.frame(age_buckets, count_ages)

#age_df <-as.data.frame(t(age_df))

#a <- barplot(age_df$,
             xlab = "age_buckets",
             ylab = "count_ages" )

#age_df <- data.frame(age_buckets, count_ages)

#age_df <-as.data.frame(t(age_df))

#a <- barplot(age_df$,
             #xlab = "age_buckets",
             #ylab = "count_ages" )
```
